name: Full HD YouTube Streamer
on:
  repository_dispatch:
    types: [start-live]

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: YouTube to Live Full HD
        run: |
          VIDEO_URL=$(yt-dlp -g -f "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]/best[height<=1080]" "https://www.youtube.com/watch?v=${{ github.event.client_payload.video_id }}")
          
          timeout 600s ffmpeg -re -i "$VIDEO_URL" \
          -c:v libx264 -preset veryfast -b:v 5000k -maxrate 5000k -bufsize 10000k \
          -pix_fmt yuv420p -s 1920x1080 -g 60 -r 30 \
          -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/${{ github.event.client_payload.stream_key }}"
          
